###################
# BUILD FOR LOCAL DEVELOPMENT
###################

FROM node:18 As development
# RUN curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm
RUN npm i -g pnpm

# WORKDIR /usr/src/app
WORKDIR /app

# COPY --chown=node:node pnpm-lock.yaml ./

RUN pnpm fetch --prod

COPY --chown=node:node . .
COPY package.json ./
RUN pnpm install
# RUN pnpm setup
# RUN pnpm install --global @nest/cli

USER node

